# TODO: get bind mounts to allow hot relaod
services:
  menu_server:
    build:
      context: ./menu_server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    #volumes:
      #- ./menu_server:/app  # Relative path to the menu_server directory
      #- /app/bin  # Exclude bin folder
      #- /app/obj  # Exclude obj folder
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #command: dotnet watch run # hot reload
    networks:
      - app_network

  menu_client:
    build:
      context: ./menu_client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    #volumes:
      #- ./menu_client:/app
      #- ./menu_client/node_modules:/app/menu_client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # file watching for hot relaod
    depends_on:
      - menu_server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
