services:
  menu_server:
    build:
      context: ./menu_server
      dockerfile: Dockerfile.prod
    ports:
      - "8080:5000"  # Expose menu_server on port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  # Set environment to production
    command: dotnet menu_server.dll  # Run the production version of the backend
    networks:
      - app_network

  menu_client:
    build:
      context: ./menu_client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"  # Expose menu_client on port 3000
    environment:
      - NODE_ENV=production  # Set environment to production
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
