# TODO: get bind mounts to allow hot relaod
services:
  menu_server:
    build:
      context: ./menu_server
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ./menu_server:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #command: dotnet watch run # hot reload
    networks:
      - app_network

  menu_client:
    build:
      context: ./menu_client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./menu_client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # file watching for hot relaod
    depends_on:
      - menu_server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
